### ISSUE TITLE
JavaDocs Bug: Misleading @return tag in isResidentCommand

### ISSUE THREAD

**Issue by benedictkhoomw** [AY2021S2-CS2103-T14-1/tp#126]
## Methods Affected
* `seedu.address.logic.commands.CommandResult.isResidentCommand`

## Expected
`@return` tag describes the boolean being returned.

## Actual
![image](https://user-images.githubusercontent.com/77471078/112724835-21134a00-8f50-11eb-8140-28f5e100970d.png)

**Comment by DrWala** [comment]
This method has been removed from the codebase.
