### ISSUE TITLE
JavaDocs Bug: Misleading @return tag in isRoomCommand

### ISSUE THREAD

**Issue by benedictkhoomw** [AY2021S2-CS2103-T14-1/tp#127]
## Methods Affected
* `seedu.address.logic.commands.CommandResult.isRoomCommand`

## Expected
`@return` tag describes the boolean being returned.

## Actual
![image](https://user-images.githubusercontent.com/77471078/112724909-75b6c500-8f50-11eb-9db6-377a49cb37e2.png)

**Comment by DrWala** [comment]
This method has been removed. Perhaps we can close this?

**Comment by benedictkhoomw** [comment]
Okay sure, thanks.
