### ISSUE TITLE
Inconsistent style for Parameters under features

### ISSUE THREAD

**Issue by stein414** [AY2021S2-CS2103-T14-1/tp#344]
Some are style as code
![image](https://user-images.githubusercontent.com/77445049/114011860-48dfa780-9898-11eb-99ad-00c7f8527a4c.png)

Some are not
![image](https://user-images.githubusercontent.com/77445049/114011932-58f78700-9898-11eb-9861-e1cc5099c7b8.png)

**Comment by benedictkhoomw** [comment]
Team decision: style it as in the former case.

Closed because individual team members will open their own issues if they need to.
