### ISSUE TITLE
Code Style: Inconsistent import style

### ISSUE THREAD

**Issue by benedictkhoomw** [AY2021S2-CS2103-T14-1/tp#86]
In `ParserUtil.java`, this particular method has fully qualified class names used. This is inconsistent with the overall code style and should be fixed.

![image](https://user-images.githubusercontent.com/77471078/111565704-cacb3c00-87d6-11eb-9bd8-969ab5a83c8b.png)

**Comment by stein414** [comment]
The inconsistency is due to the need to distinguish room.RoomNumber from issue.RoomNumber

**Comment by DrWala** [comment]
This import style is necessary to disambiguate between the two classes and is unavoidable.
